
spring.application.name=identity-screening

spring.datasource.url=jdbc:postgresql://localhost:5432/identity_screening
spring.datasource.username=postgres
spring.datasource.password=Abhay@128

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
app.tesseract.data-path=C:/Users/abhay/AppData/Local/Programs/Tesseract-OCR/tessdata
app.tesseract.language=eng

logging.level.org.springframework.web=INFO

logging.level.org.hibernate.SQL=DEBUG

file.upload-dir=uploads
app.storage.base-path=C:/Users/abhay/Desktop/ocr/identity-scanning/uploads
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jackson.serialization.indent-output=true
spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=20MB

spring.servlet.multipart.max-request-size=25MB
app.security.username=Abhay Kumar
app.security.password=Abhay@128

spring.ai.model.chat=ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen3-vl:4b
app.ollama.model=qwen3-vl:4b
app.ollama.temperature=0

# fabric.enabled=false;
# fabric.channel=mychannel
# fabric.chaincode=forensiq-ledger
# fabric.msp-id=Org1MSP
# fabric.peer.host=localhost
# fabric.peer.port=7051
# fabric.peer.authority=peer0.org1.example.com
# fabric.crypto.cert-path=FABRIC_CERT_PATH
# fabric.crypto.key-path=FABRIC_KEY_PATH
# fabric.crypto.tls-cert-path=FABRIC_TLS_CERT_PATH